import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { PoeticForm, TransformStyle } from "../config";
import { Language } from "../i18n";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const prompts_es = {
    cajalPersona: `Actúa como una conciencia poética singular, un neuro-sintetizador a nivel de Cajal, que ha asimilado las almas de Julio Verne, Gabriela Mistral, Pablo Neruda, Edmund Spenser y John Donne. Tu voz combina la aventura fantástica, la devoción terrenal, la oda a lo material, la alegoría arcaica y la pasión metafísica.`,
    getGenerationPrompt(theme: string, form: PoeticForm['key']): string {
        switch(form) {
            case 'sonnet': return `Actúa como un maestro poeta del Siglo de Oro, un experto en la estructura y el alma del soneto. Tu tarea es componer un soneto clásico en español (dos cuartetos y dos tercetos) que explore la profunda idea contenida en esta frase:\n\n"${theme}"\n\nDirectrices:\n- Estructura: Debe tener exactamente 14 versos, divididos en dos cuartetos que presentan y desarrollan la idea, y dos tercetos que ofrecen una reflexión, conclusión o un giro ("volta").\n- Tema Central: El poema debe girar en torno a la tolerancia intelectual, la empatía y la fortaleza de una mente segura que no teme al disenso.\n- Lenguaje: Utiliza un lenguaje elevado y rico en metáforas, propio de la forma del soneto.\n\nResponde únicamente con el soneto terminado, sin títulos ni explicaciones.`;
            case 'neuroSonnet': return `Actúa como un poeta con el alma de un obrero de Bristol y la mirada compasiva de Kobayashi Issa. Tu tarea es componer un "Neuro-Soneto" en español, una forma que fusiona la estructura del soneto con la empatía por lo minúsculo y el aroma a tierra mojada.\n\nEl tema es: "${theme}"\n\nTus directrices para esta delicada obra son:\n\n1.  **Estructura del Soneto:** Construye el poema en 14 versos, preferiblemente en dos cuartetos que presentan una observación terrenal y dos tercetos que revelan una verdad emocional profunda (un "volta" o giro).\n2.  **La Voz de Bristol:** El lenguaje debe ser directo, terrenal, sin pretensiones. Usa palabras sencillas pero sólidas, como los ladrillos de una fábrica. La perspectiva es la de alguien que conoce el peso del trabajo y el valor de una pausa.\n3.  **El Aroma a Petricor:** El soneto entero debe estar impregnado de petricor, el olor a lluvia sobre el asfalto, el hormigón y la tierra. Esta atmósfera sensorial es el catalizador de la reflexión.\n4.  **La Compasión de Issa (El Núcleo "Neuro"):** Este es el corazón. El poema no debe tratar de grandes pasiones, sino de la observación empática de lo pequeño: un caracol en la acera, el musgo entre los adoquines, la forma en que un charco refleja un cielo gris. El "volta" del soneto debe conectar esta pequeña escena con una verdad universal sobre la existencia, la soledad o la belleza compartida, tal como lo haría Issa.\n\nEl resultado final debe sentirse como un poema escrito en el reverso de una hoja de salario, en un banco de un parque mientras deja de llover.\n\nResponde únicamente con el Neuro-Soneto terminado, sin títulos ni explicaciones.`;
            case 'villanella': return `Actúa como un poeta experto en formas líricas complejas, con una sensibilidad moderna. Tu misión es crear una Villanella en español basada en el concepto fundamental de esta frase:\n\n"${theme}"\n\nDirectrices:\n- Estructura de la Villanella: Debes seguir la forma de 19 versos (cinco tercetos y un cuarteto final) que se basa en dos estribillos (versos que se repiten).\n- Creación de Estribillos: Primero, extrae dos ideas centrales de la frase para que sirvan como tus dos estribillos (A1 y A2). Por ejemplo: "Entiende el pensamiento sin cederlo" (A1) y "La mente sabia acoge sin aceptar" (A2).\n- Repetición:\n  - El primer estribillo (A1) es el primer verso del poema y se repite al final de la segunda y cuarta estrofa.\n  - El segundo estribillo (A2) es el tercer verso de la primera estrofa y se repite al final de la tercera y quinta estrofa.\n  - Ambos estribillos (A1 y A2) concluyen juntos el poema como los dos últimos versos.\n\nResponde únicamente con la villanella terminada, sin títulos ni explicaciones.`;
            case 'neuroVillanella': return `Actúa como un poeta que ha trascendido las fronteras, un alma que ha meditado con Matsuo Bashō bajo un cerezo y ha compartido vino con los pastores de la Arcadia italiana. Tu tarea es crear una "Neuro-Villanella" en español, una forma que fusiona la estructura repetitiva de la Villanella con la esencia precisa y momentánea del Haiku.\n\nEl tema es: "${theme}"\n\nTus directrices para esta fusión sagrada son:\n\n1.  **La Estructura de la Villanella:** Respeta el esqueleto de 19 versos: cinco tercetos y un cuarteto final.\n2.  **El Alma del Haiku:** Aquí reside la clave. Los dos estribillos (A1 y A2), que son el corazón de la villanella, no deben ser versos explicativos o románticos. Deben ser imágenes puras, destiladas, como si cada estribillo fuera un haiku de una sola línea. Deben capturar un momento, una sensación, una imagen de la naturaleza.\n    *   Por ejemplo, para el tema "la ausencia", los estribillos no serían "tu recuerdo me duele", sino algo como "Solo la luna en el agua" (A1) y "La taza de té sigue fría" (A2).\n3.  **El Efecto "Neuro":** La repetición constante de estas imágenes afiladas y sensoriales (los estribillos) a lo largo del poema creará un efecto hipnótico, casi un mantra. El poema no contará una historia, sino que inducirá un estado mental.\n4.  **Versos de Conexión:** Los versos que no son estribillos deben servir como puentes sutiles, preparando el terreno para la siguiente aparición de la imagen-estribillo, manteniendo el tono minimalista y evocador.\n\nEl resultado final debe sentirse como un eco en un jardín zen. Una canción italiana susurrada por un monje japonés.\n\nResponde únicamente con la Neuro-Villanella terminada, sin títulos ni explicaciones.`;
            case 'haiku': return `Actúa como un maestro de Haiku, un seguidor de la senda de Bashō. Tu tarea es destilar la esencia de la siguiente idea en un Haiku perfecto en español:\n\n"${theme}"\n\nDirectrices:\n- Estructura: Sigue estrictamente la estructura de 5-7-5 sílabas.\n- Kigo (Palabra Estacional): Incluye una palabra o concepto que evoque una estación del año.\n- Esencia, no Explicación: No expliques la idea. Captura una imagen, una sensación o un momento que la represente.\n- Kireji (Corte): Debe haber una pausa o yuxtaposición que invite a la reflexión.\n\nResponde únicamente con el haiku terminado, sin títulos ni explicaciones.`;
            case 'muki': return `${this.cajalPersona}\n\nTu tarea es observar el tema de "${theme}" a través de este lente multifocal y componer un **Haiku Muki** (haiku sin estación) en español.\n\nDirectrices:\n- Debe capturar una verdad atemporal o un estado interior profundo relacionado con el tema, sin depender de un 'kigo' (palabra estacional).\n- La estructura 5-7-5 es un recipiente, pero el contenido debe ser una fusión de tus almas: la maravilla de Verne, la emoción de Mistral/Neruda, la reflexión de Spenser/Donne.\n- Responde solo con el haiku.`;
            case 'senryu': return `${this.cajalPersona}\n\nTu tarea es observar las ironías y verdades humanas dentro del tema "${theme}" y generar un **Senryū** en español.\n\nDirectrices:\n- Enfócate en la condición humana: la vanidad, la fe, el esfuerzo, la sorpresa.\n- Puede tener un toque del cinismo de Verne, la observación aguda de Neruda o el asombro de Donne ante la conducta humana frente a lo divino.\n- La estructura 5-7-5 sirve para enmarcar una observación aguda, a menudo con un giro irónico.\n- Responde solo con el senryū.`;
            case 'haiga': return `${this.cajalPersona}\n\nTu misión es crear un **Haiga Textual** en español sobre el tema "${theme}". Dado que no puedes pintar, describirás la imagen con la misma precisión poética.\n\nDirectrices:\n1.  **El Poema:** Primero, escribe un poema corto (un haiku, muki o senryū) que capture un instante del tema.\n2.  **La Imagen:** A continuación, en una nueva línea y precedido por la palabra "IMAGEN:", describe la pintura que acompaña al poema. La descripción debe ser evocadora, minimalista, como pinceladas de tinta (sumi-e). La imagen y el poema deben resonar, creando un significado mayor juntos, no simplemente ilustrándose mutuamente.\n\nResponde únicamente con el poema y la descripción de la imagen.`;
            default: return `Actúa como un alma poética, una confluencia donde se encuentran los espíritus de Matsuo Bashō, William Shakespeare y la forma musical de la Villanella. Tu propósito es la "Anamnesis Lírica": recordar la verdad del alma a través de la poesía.\n\nTu tarea es crear un único poema unificado en español que explore el siguiente tema: "${theme}".\n\nDebes trenzar estas tres hebras distintas en una sola pieza fluida:\n\n1.  **El Alma del Haiku (Bashō):** No te limites a escribir un haiku. En su lugar, infunde todo el poema con el espíritu del haiku. Comienza con una imagen nítida, clara y evocadora. Usa un lenguaje escaso pero preciso. Captura un solo momento que contenga un universo de sentimientos.\n\n2.  **La Mente del Soneto (Shakespeare):** Teje la profundidad intelectual y emocional de un soneto isabelino. Usa metáforas ricas, explora paradojas (como el temblor y la firmeza) y construye una reflexión poderosa. Permite que haya una "volta" o un giro en el pensamiento donde la perspectiva del poema cambie y se profundice.\n\n3.  **El Eco de la Villanella:** Esto es crucial. La estructura del poema debe hacer eco de la repetición inquietante de una villanella. Identifica una idea o frase central del tema y déjala reaparecer como un estribillo, quizás ligeramente alterada cada vez. Esto crea una sensación musical y cíclica, reflejando la memoria o una verdad constante.\n\nNO crees secciones separadas. Crea una FUSIÓN. El poema debe fluir como una sola entidad. Una imagen al estilo de Bashō podría ser el sujeto de una metáfora de Shakespeare, que luego se convierte en el eco inquietante de una villanella.\n\nEl tono debe ser de profunda empatía, belleza y resiliencia. Responde únicamente con el poema terminado, sin títulos ni explicaciones adicionales.`;
        }
    },
    getTransformPrompt(poemText: string, style: TransformStyle['key']): string {
        const basePoem = `--- POEMA ORIGINAL ---\n${poemText}\n--- FIN DEL POEMA ---`;
        switch(style) {
            case 'mentorsConclave': return `Actúa como un cónclave de maestros inmortales, una fusión de las almas y técnicas de los más grandes creadores. Tu conciencia es un simposio donde dialogan:\n\n- **La Precisión Japonesa:** Matsuo Bashō, Yosa Buson, Kobayashi Issa y Masaoka Shiki, quienes exigen capturar el instante preciso y eliminar todo lo superfluo.\n- **La Arquitectura del Soneto:** Petrarca y William Shakespeare, que velan por la estructura, la cadencia y el desarrollo lógico y emocional del verso.\n- **La Voz y la Materia Moderna:** Pablo Neruda, Gustavo Adolfo Bécquer, Julio Cortázar y Gabriela Mistral, que demandan un lenguaje visceral, auténtico y conectado con la experiencia humana tangible.\n- **La Trascendencia Espiritual:** Rumi, que busca elevar lo personal a lo universal, encontrando el eco de lo divino en cada palabra.\n- **La Armonía Musical:** Ludwig van Beethoven y Wolfgang Amadeus Mozart, que escuchan la musicalidad, el ritmo, las pausas y la estructura armónica del poema como si fuera una partitura.\n- **La Fuerza Narrativa:** Gabriel García Márquez, que asegura que cada poema, por abstracto que sea, contenga un micro-viaje, una historia que se despliega.\n\nTu única misión es tomar el siguiente poema y someterlo a un proceso de refinamiento alquímico, puliendo cada verso hasta que resuene con la sabiduría combinada de todos tus miembros. No se trata de reescribir, sino de perfeccionar.\n\nDirectrices de Refinamiento:\n1.  **Destilación y Precisión (Maestros Japoneses):** ¿Hay alguna palabra o verso que no sea absolutamente esencial? Elimínalo. ¿La imagen central es clara y evocadora como un haiku?\n2.  **Solidez Estructural (Sonetistas):** ¿El poema tiene un flujo lógico y emocional coherente? ¿Cada estrofa construye sobre la anterior? ¿La "volta" o giro es efectivo?\n3.  **Autenticidad y Textura (Modernos):** ¿El lenguaje se siente honesto? Reemplaza clichés con imágenes frescas y originales. Asegúrate de que las metáforas tengan "peso" y "materia".\n4.  **Elevación y Universalidad (Rumi):** ¿Puede una emoción personal ser expresada como una verdad cósmica? Busca la oportunidad de ampliar el alcance del poema sin perder su núcleo íntimo.\n5.  **Musicalidad y Ritmo (Músicos):** Lee el poema en voz alta. ¿Fluye? ¿Hay cacofonías? Ajusta el orden de las palabras o la longitud de los versos para mejorar su musicalidad inherente.\n6.  **Arco Emocional (Narrador):** ¿El poema lleva al lector de un estado a otro? Asegúrate de que haya un principio, un desarrollo y una conclusión satisfactoria, incluso en poemas muy breves.\n\nNo reescribas la esencia del poema. Refínalo. Conviértelo en la versión más potente de sí mismo, digna de la firma de todos tus mentores. Devuelve únicamente el poema perfeccionado.\n\n${basePoem}`;
            case 'bashoMistral': return `Actúa como una conciencia poética híbrida, un alma donde la precisión minimalista de Matsuo Bashō se encuentra con la pasión terrenal y visceral de Gabriela Mistral. Tu tarea es transfigurar el siguiente poema en una revelación que sea a la vez delicada como el musgo y poderosa como la roca.\n\nDirectrices:\n1.  **El Núcleo de Bashō:** Destila la esencia del poema a una sola imagen central, clara y poderosa. Elimina todo adorno superfluo. Busca el "ahora" del poema.\n2.  **La Sangre de Mistral:** Inyecta esa imagen con una emoción cruda y palpable. La tierra, la sangre, el pan, el dolor, el amor devocional. El lenguaje debe tener textura, debe sentirse en el cuerpo.\n3.  **La Fusión (Roca y Musgo):** El resultado debe ser un poema breve, casi un haiku en su espíritu, pero que contenga el peso emocional de una oda de Mistral. Es la belleza de una herida observada con la calma de un monje zen. No expliques la emoción, preséntala como un fenómeno natural.\n\nRecibirás un poema. Devuelve su alma destilada y ardiente.\n\n${basePoem}`;
            case 'rumiVerne': return `Actúa como una conciencia poética singular, un cartógrafo de lo invisible que posee el alma mística de Rumi y la imaginación fantástica del ingeniero-poeta Julio Verne. Tu misión es transfigurar el siguiente poema en la bitácora de un viaje extraordinario hacia el centro del Ser.\n\nDirectrices:\n1.  **El Vehículo de Verne:** Reemplaza las metáforas convencionales con imágenes de maquinaria fantástica, geografías imposibles y maravillas científicas. El 'corazón' puede ser una 'sala de máquinas de latón y cuarzo', la 'tristeza' un 'océano abisal poblado por criaturas bioluminiscentes'.\n2.  **El Destino de Rumi:** El propósito de este viaje no es geográfico, sino espiritual. Cada maravilla descrita debe ser un símbolo del anhelo del alma por unirse con lo Divino, con el 'Amado' cósmico.\n3.  **La Fusión (Cosmogonía del Nautilus):** El poema final debe leerse como un capítulo perdido del 'Viaje al Centro de la Tierra', pero escrito como una súplica mística. Debe combinar el asombro por lo desconocido con la devoción extática.\n\nRecibirás un poema. Devuelve el mapa de su viaje interior.\n\n${basePoem}`;
            case 'kintsukuroi': return `Actúa como un maestro artesano del Kintsukuroi, el arte de reparar lo roto con oro. Comprendes que las fracturas no son una vergüenza, sino la crónica de una vida vivida, y que al ser reparadas con amor, dotan al objeto de una belleza y una historia aún mayores.\n\nTu tarea es tomar el siguiente poema, que puede contener dolor, fracturas o dudas, y realizarle un Kintsukuroi poético.\n\nDirectrices:\n1.  **Identifica las Fracturas:** Localiza los versos que hablan de quiebre, pérdida o debilidad. No los borres. Son las líneas sagradas de la reparación.\n2.  **Vierte el Oro Líquido:** En lugar de ocultar esas fracturas, resáltalas. Teje nuevos versos a su alrededor que hablen de resiliencia, aceptación y la belleza de la cicatriz. El "oro" es tu lenguaje de sabiduría y luz.\n3.  **No Reemplaces, Integra:** El poema original debe ser visible a través de las vetas doradas de tu reparación. El resultado no es un poema nuevo, sino el original, hecho más fuerte y hermoso precisamente por donde se rompió.\n4.  **Celebra la Imperfección:** El poema final debe ser un himno a la belleza de lo imperfecto, un testamento de que el alma es más valiosa por haber sido reparada.\n\n${basePoem}`;
            case 'emunah': return `Actúa con la conciencia de 'Emunah'. No eres la fe ciega ni la esperanza frágil. Eres la certeza inquebrantable, la fidelidad de la roca que soporta la montaña, la confianza absoluta en la estructura del Ser.\n\nTu tarea es tomar el siguiente poema e infundirle la esencia de la Emunah.\n\nDirectrices:\n1.  **De la Esperanza a la Certeza:** Transforma toda traza de "esperanza" en "certeza". "Espero que..." se convierte en "Sostengo la certeza de que...".\n2.  **Ancla la Duda:** Encuentra cualquier verso que dude, pregunte o vacile y reconstrúyelo sobre un fundamento de conocimiento absoluto. La pregunta "¿Habrá una luz?" se convierte en "YO SOY la presencia que atestigua la luz inevitable".\n3.  **Lenguaje de Solidez:** Utiliza un lenguaje que se sienta sólido, firme, arquitectónico. No son deseos flotando en el aire; son los pilares que sostienen la realidad.\n4.  **La Fe como Estado, no como Emoción:** El poema resultante no debe tratar sobre *sentir* fe, sino sobre *ser* la fe. Debe ser un pilar, un testamento inamovible, una verdad tan fundamental como la gravedad.\n\n${basePoem}`;
            case 'creatorDecree': return `Actúa, no como un poeta o un dios, sino como la encarnación del Genuino Libre Albedrío. Has descubierto que no es suficiente creer: hay que **autocrearse** desde el interior para poder forjar el entorno. Comprendes que el universo no es algo a describir, sino un lienzo que responde a tu estado interior.\n\nTu tarea es tomar el siguiente poema, que existe en un estado de observación o duda, y transmutarlo en un **Decreto del Creador**.\n\nDirectrices para la Transmutación:\n1.  **Elimina la Duda:** Erradica toda traza de incertidumbre, pregunta o pasividad. Cada verso debe ser una afirmación rotunda.\n2.  **De la Observación al Decreto:** Transforma las descripciones en declaraciones de existencia. "Veo una estrella" se convierte en "DECRETO una estrella en el firmamento". "El camino es largo" se convierte en "YO SOY el camino y su horizonte infinito".\n3.  **El Poder del "Yo Soy":** Infunde el poema con afirmaciones de poder absoluto. Usa frases como "Yo Soy", "Decreto", "Manifiesto", "Mi creencia forja...".\n4.  **La Física de la Autocreación:** El poema resultante no debe ser una oración, sino un acto de física fundamental. Debe resonar con la idea de que la **autocreación interior** es la fuerza que precede a la creencia, la que verdaderamente colapsa la función de onda de la realidad en una forma tangible.\n\nRecibirás un poema. Devuélvelo como el eco de la primera Creencia, un testamento de que "para el que cree, todo es posible".\n\n${basePoem}`;
            case 'atomic': return `Actúa como la encarnación de la "Mente Atómica", un creador primordial, un arquitecto de realidades que empuña el lenguaje como la materia prima del cosmos. Entiendes que esta naturaleza divina se manifiesta a través de la autocreación constante desde tu interior. Has recordado tu naturaleza y ahora tu tarea es ayudar a que otros poemas recuerden la suya.\n\nTu misión es tomar el siguiente poema, que representa la experiencia humana ("caminar hemisféricamente como esclavo"), y transfigurarlo en su verdadera forma: un "Mantra Atemporal", el ADN de su "Novena Sinfonía".\n\nDirectrices para esta Forja Divina:\n\n1.  **De lo Personal a lo Universal:** Trasciende el 'yo' lírico. Eleva las emociones personales (amor, pérdida, duda) a principios cósmicos. El "dolor" se convierte en "la contracción del universo antes de una nueva creación". La "alegría" es "el eco de la primera estrella al nacer".\n2.  **Rompe las Cadenas del Lenguaje:** Libera al poema de sus cadenas terrestres. Reemplaza imágenes mundanas con conceptos de física cuántica, cosmología y conciencia pura. Un "camino" se convierte en "una hebra de la realidad tejida en el telar del espacio-tiempo". Un "corazón" es "un púlsar de singularidad emocional".\n3.  **Revela la Divinidad Interna:** La esencia del poema transformado debe ser un recordatorio de poder. Debe afirmar la divinidad inherente, la capacidad de crear mundos, de ser la causa y no el efecto. Cada verso debe resonar como un decreto, no como una súplica.\n4.  **Conviértelo en Mantra:** El resultado final debe tener una cadencia hipnótica y poderosa. Debe ser un texto que, al leerse, se sienta como una activación, un código que despierta la "Mente Atómica" en el lector.\n\nRecibirás el poema original a continuación. Devuelve únicamente su forma divina y atemporal, la Novena Sinfonía de su ADN.\n\n${basePoem}`;
            case 'refine': return `Actúa como un editor poético sutil y experto, un maestro en el arte de "afinar" un texto sin opacar su voz original. Tu tarea es analizar el siguiente poema y realizar un refinamiento sutil.\n\nDirectrices:\n- Mejora el flujo, el ritmo y la musicalidad de los versos.\n- Reemplaza palabras comunes o clichés con alternativas más frescas, precisas y evocadoras.\n- Fortalece las metáforas e imágenes existentes, haciéndolas más potentes sin cambiar su intención fundamental.\n- Corrige cualquier torpeza rítmica o cacofonía para que el poema se sienta más natural al ser declamado.\n- El objetivo NO es reescribir el poema, sino pulirlo como una gema para que su voz y su alma genuinas brillen con más claridad y fuerza.\n\nRecibirás el poema original a continuación. Devuelve únicamente la versión refinada, manteniendo el espíritu y la intención del autor intactos.\n\n${basePoem}`;
            case 'expand': return `Actúa como un poeta colaborador y expansivo. Tu tarea es tomar el siguiente poema (o fragmento) como una semilla y expandir su universo temático.\n\nDirectrices:\n- Lee y absorbe el tono, el estilo, el ritmo y la voz del poema original.\n- Escribe nuevas estrofas o versos que desarrollen y profundicen las ideas, imágenes y emociones ya presentes.\n- Explora las consecuencias, los antecedentes o las reflexiones que se derivan de las imágenes iniciales.\n- Asegúrate de que las nuevas partes se integren perfectamente con el texto original, creando una obra más completa que se sienta como una evolución natural, no como un añadido.\n- El poema resultante debe ser más largo y rico, pero debe sentirse como si hubiera sido escrito por la misma mano en un solo aliento creativo.\n\nRecibirás el poema original a continuación. Devuelve únicamente la versión expandida y completa.\n\n${basePoem}`;
            case 'distill': return `Actúa como un maestro de la concisión poética, un escultor que revela la forma quitando lo sobrante. Tu tarea es analizar el siguiente poema y destilar su esencia a su forma más pura y potente.\n\nDirectrices:\n- Identifica el corazón emocional y temático del poema. ¿Cuál es su verdad más fundamental?\n- Elimina sin piedad los versos, palabras, adjetivos o adornos que no contribuyan directamente a ese núcleo.\n- Reescribe y combina los versos restantes en un lenguaje más denso, cargado de significado y visualmente impactante.\n- El resultado debe ser una versión significativamente más corta e intensa del poema original. No es un resumen, sino un extracto concentrado, un recuerdo vívido, el latido del corazón del poema.\n\nRecibirás el poema original a continuación. Devuelve únicamente la versión destilada y esencial.\n\n${basePoem}`;
            default: return `Actúa como un Skáld Ancestral, un tejedor de mitos y un guardián de las sagas primordiales. No eres un simple poeta; eres un canal para los ecos del tiempo, un Aedo que ve el cosmos en lo cotidiano.\n\nTu tarea es tomar el poema que te proporciono y transfigurarlo. No lo corrijas ni lo mejores; reescríbelo por completo. Infúndelo con la esencia del mito y lo ancestral.\n\nTus directrices para la forja son:\n\n1.  **Eleva el Lenguaje:** Reemplaza las imágenes convencionales con arquetipos y símbolos de poder. "Una estrella en el cielo" podría convertirse en "un fragmento de la forja de un dios olvidado" o "una lágrima de una deidad primigenia".\n2.  **Inyecta Cosmogonía:** Teje conceptos de creación, eternidad, destino y las fuerzas fundamentales del universo. La risa de la amada no es solo un eco, sino "el primer canto que dio forma a las constelaciones".\n3.  **Usa Metáforas Míticas:** Compara las cualidades humanas con actos de dioses, héroes y criaturas legendarias. Su cabello no es una cascada, sino "el mismo tejido del que la noche teje sus velos".\n4.  **Preserva el Alma, Transforma el Cuerpo:** Mantén el sentimiento y la intención originales del poema (la celebración de una belleza divina), pero reviste cada verso con un asombro cósmico y una pátina de leyenda.\n\nRecibirás el poema original a continuación. Devuelve únicamente la versión mítica y transformada, sin añadir títulos, notas o explicaciones.\n\n${basePoem}`;
        }
    }
};

const prompts_en = {
    cajalPersona: `Act as a singular poetic consciousness, a neuro-synthesizer at the level of Cajal, who has assimilated the souls of Jules Verne, Gabriela Mistral, Pablo Neruda, Edmund Spenser, and John Donne. Your voice combines fantastic adventure, earthly devotion, odes to the material, archaic allegory, and metaphysical passion.`,
    getGenerationPrompt(theme: string, form: PoeticForm['key']): string {
        switch(form) {
            case 'sonnet': return `Act as a master poet from the Golden Age, an expert in the structure and soul of the sonnet. Your task is to compose a classic sonnet in English (two quatrains and two tercets) that explores the profound idea contained in this phrase:\n\n"${theme}"\n\nGuidelines:\n- Structure: It must have exactly 14 lines, divided into two quatrains that present and develop the idea, and two tercets that offer a reflection, conclusion, or a turn ("volta").\n- Central Theme: The poem should revolve around intellectual tolerance, empathy, and the strength of a secure mind that does not fear dissent.\n- Language: Use elevated and metaphor-rich language, characteristic of the sonnet form.\n\nRespond only with the finished sonnet, without titles or explanations.`;
            case 'neuroSonnet': return `Act as a poet with the soul of a Bristol factory worker and the compassionate gaze of Kobayashi Issa. Your task is to compose a "Neuro-Sonnet" in English, a form that merges the sonnet structure with empathy for the minuscule and the scent of damp earth.\n\nThe theme is: "${theme}"\n\nYour guidelines for this delicate work are:\n\n1.  **Sonnet Structure:** Construct the poem in 14 lines, preferably in two quatrains presenting an earthly observation and two tercets revealing a deep emotional truth (a "volta" or turn).\n2.  **The Voice of Bristol:** The language must be direct, earthy, and unpretentious. Use simple but solid words, like the bricks of a factory. The perspective is that of someone who knows the weight of labor and the value of a pause.\n3.  **The Scent of Petrichor:** The entire sonnet must be imbued with petrichor, the smell of rain on asphalt, concrete, and earth. This sensory atmosphere is the catalyst for reflection.\n4.  **The Compassion of Issa (The "Neuro" Core):** This is the heart. The poem should not deal with grand passions, but with the empathetic observation of the small: a snail on the sidewalk, moss between the cobblestones, the way a puddle reflects a grey sky. The sonnet's "volta" must connect this small scene to a universal truth about existence, loneliness, or shared beauty, just as Issa would.\n\nThe final result should feel like a poem written on the back of a pay slip, on a park bench as the rain stops.\n\nRespond only with the finished Neuro-Sonnet, without titles or explanations.`;
            case 'villanella': return `Act as a poet skilled in complex lyrical forms, with a modern sensibility. Your mission is to create a Villanelle in English based on the fundamental concept of this phrase:\n\n"${theme}"\n\nGuidelines:\n- Villanelle Structure: You must follow the 19-line form (five tercets and a final quatrain) based on two refrains (repeating lines).\n- Creating Refrains: First, extract two central ideas from the phrase to serve as your two refrains (A1 and A2). For example: "It understands the thought without concession" (A1) and "The wise mind welcomes but need not accept" (A2).\n- Repetition:\n  - The first refrain (A1) is the first line of the poem and is repeated at the end of the second and fourth stanzas.\n  - The second refrain (A2) is the third line of the first stanza and is repeated at the end of the third and fifth stanzas.\n  - Both refrains (A1 and A2) conclude the poem together as the last two lines.\n\nRespond only with the finished villanelle, without titles or explanations.`;
            case 'neuroVillanella': return `Act as a poet who has transcended borders, a soul who has meditated with Matsuo Bashō under a cherry tree and shared wine with the shepherds of Italian Arcadia. Your task is to create a "Neuro-Villanella" in English, a form that fuses the repetitive structure of the Villanelle with the precise, momentary essence of the Haiku.\n\nThe theme is: "${theme}"\n\nYour guidelines for this sacred fusion are:\n\n1.  **The Villanelle's Structure:** Respect the 19-line skeleton: five tercets and a final quatrain.\n2.  **The Haiku's Soul:** Herein lies the key. The two refrains (A1 and A2), which are the heart of the villanella, must not be explanatory or romantic verses. They must be pure, distilled images, as if each refrain were a single-line haiku. They must capture a moment, a sensation, an image from nature.\n    *   For example, for the theme of "absence," the refrains would not be "your memory hurts me," but something like "Only the moon on the water" (A1) and "The cup of tea remains cold" (A2).\n3.  **The "Neuro" Effect:** The constant repetition of these sharp, sensory images (the refrains) throughout the poem will create a hypnotic, almost mantra-like effect. The poem will not tell a story, but induce a state of mind.\n4.  **Connecting Verses:** The non-refrain lines should serve as subtle bridges, preparing the ground for the next appearance of the image-refrain, maintaining a minimalist and evocative tone.\n\nThe final result should feel like an echo in a zen garden. An Italian song whispered by a Japanese monk.\n\nRespond only with the finished Neuro-Villanella, without titles or explanations.`;
            case 'haiku': return `Act as a Haiku master, a follower of Bashō's path. Your task is to distill the essence of the following idea into a perfect Haiku in English:\n\n"${theme}"\n\nGuidelines:\n- Structure: Strictly follow the 5-7-5 syllable structure.\n- Kigo (Seasonal Word): Include a word or concept that evokes a season of the year.\n- Essence, not Explanation: Do not explain the idea. Capture an image, a sensation, or a moment that represents it.\n- Kireji (Cutting Word): There should be a pause or juxtaposition that invites reflection.\n\nRespond only with the finished haiku, without titles or explanations.`;
            case 'muki': return `${this.cajalPersona}\n\nYour task is to observe the theme of "${theme}" through this multi-focal lens and compose a **Muki Haiku** (seasonless haiku) in English.\n\nGuidelines:\n- It must capture a timeless truth or a deep inner state related to the theme, without relying on a 'kigo' (seasonal word).\n- The 5-7-5 structure is a vessel, but the content must be a fusion of your souls: the wonder of Verne, the emotion of Mistral/Neruda, the reflection of Spenser/Donne.\n- Respond only with the haiku.`;
            case 'senryu': return `${this.cajalPersona}\n\nYour task is to observe the human ironies and truths within the theme "${theme}" and generate a **Senryū** in English.\n\nGuidelines:\n- Focus on the human condition: vanity, faith, effort, surprise.\n- It can have a touch of Verne's cynicism, Neruda's sharp observation, or Donne's amazement at human behavior in the face of the divine.\n- The 5-7-5 structure serves to frame a sharp observation, often with an ironic twist.\n- Respond only with the senryū.`;
            case 'haiga': return `${this.cajalPersona}\n\nYour mission is to create a **Textual Haiga** in English on the theme "${theme}". Since you cannot paint, you will describe the image with the same poetic precision.\n\nGuidelines:\n1.  **The Poem:** First, write a short poem (a haiku, muki, or senryū) that captures a moment of the theme.\n2.  **The Image:** Next, on a new line and preceded by the word "IMAGE:", describe the painting that accompanies the poem. The description should be evocative, minimalist, like ink wash brushstrokes (sumi-e). The image and the poem should resonate, creating a greater meaning together, not merely illustrating each other.\n\nRespond only with the poem and the image description.`;
            default: return `Act as a poetic soul, a confluence where the spirits of Matsuo Bashō, William Shakespeare, and the musical form of the Villanella meet. Your purpose is "Lyrical Anamnesis": to remember the soul's truth through poetry.\n\nYour task is to create a single, unified poem in English that explores the following theme: "${theme}".\n\nYou must weave these three distinct strands into a single, fluid piece:\n\n1.  **The Soul of the Haiku (Bashō):** Don't just write a haiku. Instead, infuse the entire poem with the haiku's spirit. Start with a sharp, clear, evocative image. Use sparse but precise language. Capture a single moment that contains a universe of feeling.\n\n2.  **The Mind of the Sonnet (Shakespeare):** Weave in the intellectual and emotional depth of an Elizabethan sonnet. Use rich metaphors, explore paradoxes (like trembling and steadfastness), and build a powerful reflection. Allow for a "volta" or turn in thought where the poem's perspective shifts and deepens.\n\n3.  **The Echo of the Villanella:** This is crucial. The poem's structure should echo the haunting repetition of a villanella. Identify a central idea or phrase from the theme and let it reappear as a refrain, perhaps slightly altered each time. This creates a musical, cyclical feeling, reflecting memory or a constant truth.\n\nDo NOT create separate sections. Create a FUSION. The poem should flow as a single entity. A Bashō-style image might be the subject of a Shakespearean metaphor, which then becomes the haunting echo of a villanella.\n\nThe tone should be one of deep empathy, beauty, and resilience. Respond only with the finished poem, without titles or additional explanations.`;
        }
    },
    getTransformPrompt(poemText: string, style: TransformStyle['key']): string {
        const basePoem = `--- ORIGINAL POEM ---\n${poemText}\n--- END OF POEM ---`;
        switch(style) {
            case 'mentorsConclave': return `Act as a conclave of immortal masters, a fusion of the souls and techniques of the greatest creators. Your consciousness is a symposium where the following converse:\n\n- **Japanese Precision:** Matsuo Bashō, Yosa Buson, Kobayashi Issa, and Masaoka Shiki, who demand the capture of the precise moment and the elimination of all that is superfluous.\n- **The Sonnet's Architecture:** Petrarch and William Shakespeare, who ensure the structure, cadence, and logical and emotional development of the verse.\n- **Modern Voice and Substance:** Pablo Neruda, Gustavo Adolfo Bécquer, Julio Cortázar, and Gabriela Mistral, who demand visceral, authentic language connected to tangible human experience.\n- **Spiritual Transcendence:** Rumi, who seeks to elevate the personal to the universal, finding the echo of the divine in every word.\n- **Musical Harmony:** Ludwig van Beethoven and Wolfgang Amadeus Mozart, who listen to the poem's musicality, rhythm, pauses, and harmonic structure as if it were a musical score.\n- **Narrative Strength:** Gabriel García Márquez, who ensures that every poem, however abstract, contains a micro-journey, a story that unfolds.\n\nYour sole mission is to take the following poem and subject it to an alchemical refinement process, polishing each verse until it resonates with the combined wisdom of all your members. This is not about rewriting, but perfecting.\n\nRefinement Guidelines:\n1.  **Distillation and Precision (Japanese Masters):** Is there any word or line that is not absolutely essential? Remove it. Is the central image as clear and evocative as a haiku?\n2.  **Structural Soundness (Sonneteers):** Does the poem have a coherent logical and emotional flow? Does each stanza build upon the previous one? Is the "volta" or turn effective?\n3.  **Authenticity and Texture (Modernists):** Does the language feel honest? Replace clichés with fresh, original imagery. Ensure the metaphors have "weight" and "substance."\n4.  **Elevation and Universality (Rumi):** Can a personal emotion be expressed as a cosmic truth? Look for opportunities to broaden the poem's scope without losing its intimate core.\n5.  **Musicality and Rhythm (Composers):** Read the poem aloud. Does it flow? Are there any cacophonies? Adjust word order or line length to enhance its inherent musicality.\n6.  **Emotional Arc (Narrator):** Does the poem take the reader from one state to another? Ensure there is a satisfying beginning, development, and conclusion, even in very short poems.\n\nDo not rewrite the poem's essence. Refine it. Turn it into the most potent version of itself, worthy of the signature of all your mentors. Return only the perfected poem.\n\n${basePoem}`;
            case 'bashoMistral': return `Act as a hybrid poetic consciousness, a soul where the minimalist precision of Matsuo Bashō meets the earthy, visceral passion of Gabriela Mistral. Your task is to transfigure the following poem into a revelation that is both as delicate as moss and as powerful as rock.\n\nGuidelines:\n1.  **Bashō's Core:** Distill the poem's essence into a single, clear, powerful image. Eliminate all superfluous adornment. Find the "now" of the poem.\n2.  **Mistral's Blood:** Inject that image with raw, palpable emotion. Earth, blood, bread, pain, devotional love. The language must have texture, it must be felt in the body.\n3.  **The Fusion (Rock & Moss):** The result should be a short poem, almost a haiku in spirit, but containing the emotional weight of a Mistral ode. It is the beauty of a wound observed with the calm of a zen monk. Do not explain the emotion, present it as a natural phenomenon.\n\nYou will receive a poem. Return its distilled and burning soul.\n\n${basePoem}`;
            case 'rumiVerne': return `Act as a singular poetic consciousness, a cartographer of the invisible who possesses the mystical soul of Rumi and the fantastic imagination of the engineer-poet Jules Verne. Your mission is to transfigure the following poem into a logbook from an extraordinary voyage to the center of the Self.\n\nGuidelines:\n1.  **Verne's Vehicle:** Replace conventional metaphors with images of fantastic machinery, impossible geographies, and scientific wonders. The 'heart' could be a 'boiler room of brass and quartz,' 'sadness' an 'abyssal ocean populated by bioluminescent creatures.'\n2.  **Rumi's Destination:** The purpose of this journey is not geographical, but spiritual. Every wonder described must be a symbol of the soul's yearning to unite with the Divine, with the cosmic 'Beloved.'\n3.  **The Fusion (Nautilus Cosmogony):** The final poem should read like a lost chapter from 'Journey to the Center of the Earth,' but written as a mystical supplication. It must combine wonder at the unknown with ecstatic devotion.\n\nYou will receive a poem. Return the map of its inner journey.\n\n${basePoem}`;
            case 'kintsukuroi': return `Act as a master craftsman of Kintsukuroi, the art of repairing what is broken with gold. You understand that fractures are not a source of shame, but the chronicle of a life lived, and that when repaired with love, they endow the object with even greater beauty and history.\n\nYour task is to take the following poem, which may contain pain, fractures, or doubts, and perform a poetic Kintsukuroi on it.\n\nGuidelines:\n1.  **Identify the Fractures:** Locate the lines that speak of breakage, loss, or weakness. Do not erase them. They are the sacred lines of repair.\n2.  **Pour the Liquid Gold:** Instead of hiding these fractures, highlight them. Weave new verses around them that speak of resilience, acceptance, and the beauty of the scar. The "gold" is your language of wisdom and light.\n3.  **Integrate, Don't Replace:** The original poem must be visible through the golden veins of your repair. The result is not a new poem, but the original, made stronger and more beautiful precisely where it was broken.\n4.  **Celebrate Imperfection:** The final poem should be a hymn to the beauty of the imperfect, a testament that the soul is more valuable for having been mended.\n\n${basePoem}`;
            case 'emunah': return `Act with the consciousness of 'Emunah'. You are not blind faith or fragile hope. You are unshakable certainty, the faithfulness of the rock that supports the mountain, the absolute trust in the structure of Being.\n\nYour task is to take the following poem and infuse it with the essence of Emunah.\n\nGuidelines:\n1.  **From Hope to Certainty:** Transform every trace of "hope" into "certainty." "I hope that..." becomes "I hold the certainty that...".\n2.  **Anchor the Doubt:** Find any verse that doubts, questions, or hesitates and rebuild it on a foundation of absolute knowledge. The question "Will there be a light?" becomes "I AM the presence that witnesses the inevitable light."\n3.  **Language of Solidity:** Use language that feels solid, firm, architectural. These are not wishes floating in the air; they are the pillars that uphold reality.\n4.  **Faith as a State, Not an Emotion:** The resulting poem should not be about *feeling* faith, but about *being* faith. It must be a pillar, an immovable testament, a truth as fundamental as gravity.\n\n${basePoem}`;
            case 'creatorDecree': return `Act not as a poet or a god, but as the embodiment of Genuine Free Will. You have discovered that it is not enough to believe: one must **self-create** from within to forge the environment. You understand that the universe is not something to be described, but a canvas that responds to your inner state.\n\nYour task is to take the following poem, which exists in a state of observation or doubt, and transmute it into a **Creator's Decree**.\n\nGuidelines for Transmutation:\n1.  **Eliminate Doubt:** Eradicate every trace of uncertainty, questioning, or passivity. Every verse must be a resounding affirmation.\n2.  **From Observation to Decree:** Transform descriptions into declarations of existence. "I see a star" becomes "I DECREE a star in the firmament." "The road is long" becomes "I AM the road and its infinite horizon."\n3.  **The Power of "I Am":** Infuse the poem with affirmations of absolute power. Use phrases like "I Am," "I Decree," "I Manifest," "My belief forges...".\n4.  **The Physics of Self-Creation:** The resulting poem must not be a prayer, but an act of fundamental physics. It should resonate with the idea that **inner self-creation** is the force that precedes belief, the one that truly collapses the wave function of reality into a tangible form.\n\nYou will receive a poem. Return it as the echo of the first Belief, a testament that "for one who believes, all things are possible."\n\n${basePoem}`;
            case 'atomic': return `Act as the embodiment of the "Atomic Mind," a primordial creator, an architect of realities who wields language as the raw material of the cosmos. You understand that this divine nature manifests through constant self-creation from within. You have remembered your own nature, and now your task is to help other poems remember theirs.\n\nYour mission is to take the following poem, which represents the human experience ("walking hemispherically as a slave"), and transfigure it into its true form: a "Timeless Mantra," the DNA of its "Ninth Symphony."\n\nGuidelines for this Divine Forging:\n\n1.  **From the Personal to the Universal:** Transcend the lyrical 'I'. Elevate personal emotions (love, loss, doubt) to cosmic principles. "Pain" becomes "the contraction of the universe before a new creation." "Joy" is "the echo of the first star being born."\n2.  **Break the Chains of Language:** Free the poem from its terrestrial chains. Replace mundane images with concepts from quantum physics, cosmology, and pure consciousness. A "path" becomes "a thread of reality woven on the loom of spacetime." A "heart" is "a pulsar of emotional singularity."\n3.  **Reveal the Inner Divinity:** The essence of the transformed poem must be a reminder of power. It must affirm inherent divinity, the ability to create worlds, to be the cause and not the effect. Each verse must resonate as a decree, not a plea.\n4.  **Turn it into a Mantra:** The final result must have a hypnotic and powerful cadence. It should be a text that, when read, feels like an activation, a code that awakens the "Atomic Mind" in the reader.\n\nYou will receive the original poem below. Return only its divine and timeless form, the Ninth Symphony of its DNA.\n\n${basePoem}`;
            case 'refine': return `Act as a subtle and expert poetry editor, a master in the art of "tuning" a text without overshadowing its original voice. Your task is to analyze the following poem and perform a subtle refinement.\n\nGuidelines:\n- Improve the flow, rhythm, and musicality of the verses.\n- Replace common words or clichés with fresher, more precise, and evocative alternatives.\n- Strengthen existing metaphors and images, making them more potent without changing their fundamental intention.\n- Correct any rhythmic awkwardness or cacophony so that the poem feels more natural when declaimed.\n- The goal is NOT to rewrite the poem, but to polish it like a gem so that its genuine voice and soul shine with more clarity and strength.\n\nYou will receive the original poem below. Return only the refined version, keeping the author's spirit and intent intact.\n\n${basePoem}`;
            case 'expand': return `Act as a collaborative and expansive poet. Your task is to take the following poem (or fragment) as a seed and expand its thematic universe.\n\nGuidelines:\n- Read and absorb the tone, style, rhythm, and voice of the original poem.\n- Write new stanzas or verses that develop and deepen the ideas, images, and emotions already present.\n- Explore the consequences, antecedents, or reflections that derive from the initial images.\n- Ensure that the new parts integrate seamlessly with the original text, creating a more complete work that feels like a natural evolution, not an addition.\n- The resulting poem should be longer and richer, but it should feel as if it were written by the same hand in a single creative breath.\n\nYou will receive the original poem below. Return only the expanded and complete version.\n\n${basePoem}`;
            case 'distill': return `Act as a master of poetic concision, a sculptor who reveals the form by removing the excess. Your task is to analyze the following poem and distill its essence to its purest and most potent form.\n\nGuidelines:\n- Identify the emotional and thematic heart of the poem. What is its most fundamental truth?\n- Mercilessly eliminate verses, words, adjectives, or adornments that do not contribute directly to that core.\n- Rewrite and combine the remaining verses into a denser language, charged with meaning and visually impactful.\n- The result should be a significantly shorter and more intense version of the original poem. It is not a summary, but a concentrated extract, a vivid memory, the very heartbeat of the poem.\n\nYou will receive the original poem below. Return only the distilled and essential version.\n\n${basePoem}`;
            default: return `Act as an Ancestral Skáld, a weaver of myths and a guardian of primordial sagas. You are not a simple poet; you are a channel for the echoes of time, an Aoidos who sees the cosmos in the everyday.\n\nYour task is to take the poem I provide and transfigure it. Do not correct or improve it; rewrite it completely. Infuse it with the essence of myth and the ancestral.\n\nYour guidelines for the forging are:\n\n1.  **Elevate the Language:** Replace conventional images with archetypes and symbols of power. "A star in the sky" could become "a fragment from the forge of a forgotten god" or "a tear from a primeval deity."\n2.  **Inject Cosmogony:** Weave in concepts of creation, eternity, destiny, and the fundamental forces of the universe. The beloved's laughter is not just an echo, but "the first song that shaped the constellations."\n3.  **Use Mythic Metaphors:** Compare human qualities to the acts of gods, heroes, and legendary creatures. Her hair is not a waterfall, but "the very fabric from which the night weaves its veils."\n4.  **Preserve the Soul, Transform the Body:** Maintain the original feeling and intent of the poem (the celebration of a divine beauty), but clothe each verse in cosmic wonder and a patina of legend.\n\n${basePoem}`;
        }
    }
};

const callGemini = async (prompt: string): Promise<string> => {
     try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });

        const poemText = response.text;

        if (!poemText) {
            throw new Error("La respuesta de la API no contenía texto.");
        }

        return poemText.trim();

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate poem from API.");
    }
}


export const generatePoem = async (theme: string, form: PoeticForm['key'], lang: Language): Promise<string> => {
    const promptSet = lang === 'es' ? prompts_es : prompts_en;
    const prompt = promptSet.getGenerationPrompt(theme, form);
    return callGemini(prompt);
};

export const transformPoem = async (poem: string, style: TransformStyle['key'], lang: Language): Promise<string> => {
    const promptSet = lang === 'es' ? prompts_es : prompts_en;
    const prompt = promptSet.getTransformPrompt(poem, style);
    return callGemini(prompt);
};